<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>IndexLens Debug</title>
    <style>
        :root {
            --bg: #0f172a;
            --panel: #111827;
            --text: #e5e7eb;
            --accent: #14b8a6;
            --muted: #94a3b8;
            --danger: #ef4444;
            --warn: #f59e0b;
            --ok: #22c55e;
        }
        body {
            margin: 0;
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            background: radial-gradient(circle at top right, #1f2937, var(--bg));
            color: var(--text);
        }
        .container {
            max-width: 1100px;
            margin: 24px auto;
            padding: 0 16px;
        }
        .card {
            background: linear-gradient(160deg, rgba(20, 184, 166, 0.12), rgba(17, 24, 39, 0.9));
            border: 1px solid rgba(148, 163, 184, 0.25);
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 16px;
        }
        h1, h2 {
            margin: 0 0 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px;
            border-bottom: 1px solid rgba(148, 163, 184, 0.2);
            text-align: left;
        }
        .muted { color: var(--muted); }
        .critical { color: var(--danger); font-weight: 700; }
        .high { color: var(--warn); font-weight: 700; }
        .good { color: var(--ok); font-weight: 700; }
    </style>
</head>
<body>
<div class="container">
    <div class="card">
        <h1>IndexLens Runtime Debug</h1>
        <p class="muted">Snapshot generated by IndexLens route profiler.</p>
    </div>

    <div class="card">
        <h2>Route Heatmap</h2>
        <table>
            <thead>
            <tr>
                <th>Route</th>
                <th>Avg Queries</th>
                <th>Avg SQL Time</th>
                <th>Severity</th>
            </tr>
            </thead>
            <tbody>
            @forelse(($routes ?? []) as $route)
                <tr>
                    <td>{{ $route['route'] }}</td>
                    <td>{{ $route['average_query_count'] }}</td>
                    <td>{{ $route['average_sql_time_ms'] }}ms</td>
                    <td class="{{ strtolower($route['severity']) }}">{{ strtoupper($route['severity']) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No route data yet.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
</div>
</body>
</html>
